# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about' # this is the about.md file under content/home
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Publications
    #url: '#featured'
    #url: 'publication' 
    #url: 'publication/' ##this is the "publication"" folder under "content" but outside "home"
    #weight: 61
  # - name: Courses
  #   url: courses/
  #   weight: 60
  - name: Teaching
    url: "teaching/" #this is the teaching.md file under "content"
    weight: 50
  - name: Publications
    url: "publication_ver2/" #this is the teaching.md file under "content"
    weight: 51
  - name: Contact
     #url: '#contact' #this is the contact.md file under content/home
    url: '/ContactPage' #this finds the folder content/ContactPage underwhich is the "contact.md" file
    weight: 80

